#!/bin/bash

module load comp-intel/2018.3.222 mpi-hpe/mpt.2.25 hdf4/4.2.12 hdf5/1.8.18_mpt netcdf/4.4.1.1_mpt

rm -f *.o
rm -f *.f
make CLEAN
rm Makefile

../../../tools/genmake2 "-mpi" "-mods" "../code_ad_obsfit" "-optfile" "../../pleiades_build_options/linux_amd64_ifort+mpi_ice_nas"
make depend
make -j 4

